PERMISSION_SES_ADMIN = 'ses_admin'
PERMISSION_SES_STAFF = 'ses_staff'
PERMISSION_PI_ADMIN = 'pi_admin'
PERMISSION_CD_ADMIN = 'cd_admin'
PERMISSION_USER = 'user'
PERMISSION_CHOICES = (
    (PERMISSION_SES_ADMIN, 'SES Admin'),
    (PERMISSION_SES_STAFF, 'SES Staff'),
    (PERMISSION_PI_ADMIN, 'PI Admin'),
    (PERMISSION_CD_ADMIN, 'CD Admin'),
    (PERMISSION_USER, 'Registered User'),
)
PERMISSIONS_SUPERUSER_ONLY = []
PERMISSIONS_SES_ADMIN_ONLY = [PERMISSION_SES_ADMIN]
PERMISSIONS_SES_STAFF_AND_ABOVE = [PERMISSION_SES_ADMIN, PERMISSION_SES_STAFF]
PERMISSIONS_PI_ADMIN_AND_ABOVE = [PERMISSION_SES_ADMIN, PERMISSION_SES_STAFF,
                                  PERMISSION_PI_ADMIN]
PERMISSIONS_CD_ADMIN_AND_ABOVE = [PERMISSION_SES_ADMIN, PERMISSION_SES_STAFF,
                                  PERMISSION_PI_ADMIN, PERMISSION_CD_ADMIN]
PERMISSIONS_USER_AND_ABOVE = [PERMISSION_SES_ADMIN, PERMISSION_SES_STAFF,
                              PERMISSION_PI_ADMIN, PERMISSION_CD_ADMIN,
                              PERMISSION_USER]

